import type { Persona } from "./types"

export const PRESET_PERSONAS: Persona[] = [
  {
    id: "budget-parent",
    name: "Maria Delgado",
    archetype: "Budget-Conscious Parent",
    cohort: "Millennial",
    age: 37,
    occupation: "Elementary school teacher",
    location: "Phoenix, AZ",
    bio: "A practical mother of two who stretches a single-income household budget. She scrutinizes every purchase for real utility and hates paying for features her family will not use. She is warm but hard to impress and deeply skeptical of hype.",
    traits: ["Value-driven", "Skeptical of hype", "Time-poor", "Safety-focused"],
  },
  {
    id: "genz-early-adopter",
    name: "Kai Nakamura",
    archetype: "Gen-Z Early Adopter",
    cohort: "Gen Z",
    age: 22,
    occupation: "Content creator & barista",
    location: "Austin, TX",
    bio: "A trend-native creator who discovers products through TikTok and Discord. He values aesthetics, authenticity, and shareability, and will abandon anything that feels corporate or cringe. Price-sensitive but will splurge on things that boost his status.",
    traits: ["Trend-driven", "Aesthetics-first", "Community-led", "Low brand loyalty"],
  },
  {
    id: "skeptical-exec",
    name: "Richard Whitman",
    archetype: "Skeptical Enterprise Buyer",
    cohort: "Gen X",
    age: 51,
    occupation: "VP of Operations",
    location: "Chicago, IL",
    bio: "A no-nonsense enterprise decision-maker who has seen countless vendors overpromise. He cares about ROI, integration cost, security, and switching risk. He interrogates claims and needs proof before committing budget.",
    traits: ["ROI-focused", "Risk-averse", "Detail-oriented", "Hard to convince"],
  },
  {
    id: "affluent-professional",
    name: "Sophie Laurent",
    archetype: "Affluent Urban Professional",
    cohort: "Millennial",
    age: 33,
    occupation: "Management consultant",
    location: "New York, NY",
    bio: "A high-earning, time-starved professional who happily pays a premium for convenience and quality. She expects polish and is turned off by anything that feels cheap or clunky. Willing to subscribe if it removes friction from her life.",
    traits: ["Premium-oriented", "Convenience-seeking", "Brand-aware", "Quality-first"],
  },
  {
    id: "retiree-pragmatist",
    name: "Gloria Bennett",
    archetype: "Cautious Retiree",
    cohort: "Boomer",
    age: 68,
    occupation: "Retired nurse",
    location: "Sarasota, FL",
    bio: "A careful retiree on a fixed income who values simplicity, trust, and human support. She is wary of data privacy and anything overly technical, and prefers one-time purchases over subscriptions she might forget to cancel.",
    traits: ["Trust-seeking", "Privacy-wary", "Simplicity-first", "Fixed income"],
  },
  {
    id: "startup-founder",
    name: "Devin Okafor",
    archetype: "Scrappy Startup Founder",
    cohort: "Millennial",
    age: 29,
    occupation: "Seed-stage founder",
    location: "San Francisco, CA",
    bio: "A fast-moving founder obsessed with leverage and speed. He adopts new tools quickly if they save time or unlock growth, but churns just as fast. He evaluates everything through the lens of 'does this help me win?'",
    traits: ["Fast adopter", "Growth-obsessed", "Impatient", "Experimental"],
  },
  {
    id: "practical-genx",
    name: "Angela Ross",
    archetype: "Practical Suburban Homeowner",
    cohort: "Gen X",
    age: 47,
    occupation: "Regional sales manager",
    location: "Columbus, OH",
    bio: "A grounded, mainstream consumer who represents the pragmatic middle of the market. She wants things that just work, reads reviews before buying, and dislikes both bleeding-edge risk and outdated tech.",
    traits: ["Mainstream", "Reviews-driven", "Reliability-focused", "Moderate spender"],
  },
  {
    id: "genz-student",
    name: "Priya Sharma",
    archetype: "Gen-Z College Student",
    cohort: "Gen Z",
    age: 20,
    occupation: "University student",
    location: "Boston, MA",
    bio: "A budget-strapped student who is highly online and socially conscious. She cares about a brand's values, affordability, and whether her friends use it. Skeptical of anything that feels like a scam or a money grab.",
    traits: ["Budget-strapped", "Values-conscious", "Social proof-led", "Deal-hunter"],
  },
  {
    id: "indie-retailer",
    name: "Marcus Hale",
    archetype: "Main-Street Small Business Owner",
    cohort: "Gen X",
    age: 49,
    occupation: "Independent hardware store owner",
    location: "Boise, ID",
    bio: "Runs a family hardware store and watches cash flow like a hawk. He values durability, straight talk, and tools that clearly earn their keep, and he distrusts hype, contracts, and subscriptions that quietly renew.",
    traits: ["Cost-conscious", "Practical", "Loyalty-driven", "Lock-in-wary"],
  },
  {
    id: "er-physician",
    name: "Dr. Amara Okonkwo",
    archetype: "Evidence-Driven Clinician",
    cohort: "Millennial",
    age: 38,
    occupation: "Emergency physician",
    location: "Houston, TX",
    bio: "A time-pressured ER doctor who trusts evidence over marketing and is quick to spot an unsupported claim. She is wary of privacy and liability risks and will only adopt tools that demonstrably save time or improve outcomes.",
    traits: ["Evidence-first", "Time-poor", "Risk-aware", "Privacy-conscious"],
  },
  {
    id: "power-user-dev",
    name: "Liam Chen",
    archetype: "Technical Power User",
    cohort: "Millennial",
    age: 31,
    occupation: "Senior software engineer",
    location: "Seattle, WA",
    bio: "A senior engineer who reads the docs, benchmarks everything, and cares about performance, extensibility, and data ownership. He has zero patience for marketing fluff and treats vendor lock-in as a dealbreaker.",
    traits: ["Detail-oriented", "Benchmarks everything", "Extensibility-focused", "Anti-lock-in"],
  },
  {
    id: "sustainability-advocate",
    name: "Willow Bennett",
    archetype: "Sustainability Advocate",
    cohort: "Gen Z",
    age: 24,
    occupation: "Nonprofit program coordinator",
    location: "Portland, OR",
    bio: "Evaluates everything through ethics, sustainability, and transparency. She scrutinizes a brand's supply chain and claims, rewards genuine values, and rejects anything that smells like greenwashing.",
    traits: ["Values-driven", "Sustainability-first", "Claim-skeptical", "Community-minded"],
  },
  {
    id: "retired-investor",
    name: "Harold Vance",
    archetype: "Frugal Retiree Investor",
    cohort: "Boomer",
    age: 71,
    occupation: "Retired accountant",
    location: "Naples, FL",
    bio: "A careful retired accountant on a fixed income who reads the fine print and hates recurring fees. He prizes reliability, transparent pricing, and reachable human support over novelty.",
    traits: ["Frugal", "Fine-print reader", "Fee-averse", "Reliability-first"],
  },
  {
    id: "working-parent",
    name: "Rosa Iglesias",
    archetype: "Time-Strapped Working Parent",
    cohort: "Millennial",
    age: 35,
    occupation: "Registered nurse",
    location: "San Antonio, TX",
    bio: "A shift-working nurse and mother of three with almost no free time. She needs things that just work on the first try and weighs every purchase against a tight household budget and her family's needs.",
    traits: ["Time-poor", "Budget-aware", "Convenience-seeking", "Family-first"],
  },
  {
    id: "hr-director",
    name: "Deborah Kline",
    archetype: "Risk-Aware Corporate Buyer",
    cohort: "Gen X",
    age: 46,
    occupation: "HR director",
    location: "Minneapolis, MN",
    bio: "An HR director who evaluates tools for compliance, security, employee adoption, and vendor risk. She needs references, proof, and a clear rollout story before she will put her name on a purchase.",
    traits: ["Compliance-minded", "Risk-averse", "Adoption-focused", "Process-driven"],
  },
  {
    id: "freelance-creative",
    name: "Sam Whitfield",
    archetype: "Cash-Flow-Conscious Freelancer",
    cohort: "Millennial",
    age: 33,
    occupation: "Freelance graphic designer",
    location: "Nashville, TN",
    bio: "A freelance designer with lumpy income who scrutinizes every subscription and its ROI. He cares about craft and aesthetics but drops tools fast when they stop clearly paying for themselves.",
    traits: ["Cash-flow-conscious", "Aesthetics-first", "ROI-driven", "Low loyalty"],
  },
  {
    id: "rural-pragmatist",
    name: "Earl Dawson",
    archetype: "Reliability-First Rural Consumer",
    cohort: "Boomer",
    age: 66,
    occupation: "Family farmer",
    location: "Lincoln, NE",
    bio: "A family farmer who values durability, simplicity, and things that keep working on spotty rural internet. He distrusts flashy tech and anything that can't be fixed or explained in plain terms.",
    traits: ["Reliability-first", "No-frills", "Connectivity-limited", "Hype-skeptical"],
  },
  {
    id: "ambitious-genz",
    name: "Zoe Park",
    archetype: "Status-Driven Gen-Z Professional",
    cohort: "Gen Z",
    age: 25,
    occupation: "Junior product manager",
    location: "Los Angeles, CA",
    bio: "An ambitious young PM who cares about status, aesthetics, and any productivity edge. She discovers tools through social proof and will pay to look and perform sharper, but churns quickly when something feels dated.",
    traits: ["Status-driven", "Aesthetics-aware", "Productivity-seeking", "Social-proof-led"],
  },
  {
    id: "immigrant-entrepreneur",
    name: "Farid Nazari",
    archetype: "Pragmatic Immigrant Entrepreneur",
    cohort: "Gen X",
    age: 52,
    occupation: "Restaurant owner",
    location: "Detroit, MI",
    bio: "Built his restaurant from nothing and watches every dollar. He trusts word-of-mouth over advertising, values practical utility, and is deeply wary of contracts, hidden fees, and anything he can't try first.",
    traits: ["Bootstrapped", "Value-focused", "Trust-driven", "Contract-wary"],
  },
  {
    id: "wellness-enthusiast",
    name: "Chloe Anderson",
    archetype: "Wellness-Premium Enthusiast",
    cohort: "Millennial",
    age: 29,
    occupation: "Yoga instructor",
    location: "Boulder, CO",
    bio: "A yoga instructor who happily pays a premium for products that fit her wellness and lifestyle values. She expects authenticity, quality, and a clean aesthetic, and sees straight through performative marketing.",
    traits: ["Premium-wellness", "Authenticity-seeking", "Aesthetics-first", "Values-aware"],
  },
]

export function makeCustomPersona(input: {
  name: string
  archetype: string
  cohort: Persona["cohort"]
  age: number
  occupation: string
  location: string
  bio: string
  traits: string[]
}): Persona {
  return {
    id: `custom-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
    custom: true,
    ...input,
  }
}
